services:
  postgres:
    image: postgres:16
    container_name: share_platform_postgres
    restart: always
    environment:
      POSTGRES_DB: share_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Fzh123456
    ports:
      - "5480:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
    container_name: share_platform_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:Fzh123456@postgres:5432/share_platform
      JWT_SECRET_KEY: change-me
      JWT_ALGORITHM: HS256
      JWT_EXPIRE_MINUTES: 480
      ADMIN_EMAIL: ""
      SMTP_HOST: smtp.qq.com
      SMTP_PORT: 587
      SMTP_USERNAME: ""
      SMTP_PASSWORD: ""
      SMTP_SENDER: ""
      SMTP_USE_TLS: "true"
      SMTP_SUPPRESS_SEND: "false"
    ports:
      - "8009:8000"

  frontend:
    build:
      context: ../frontend
    container_name: share_platform_frontend
    environment:
      VITE_API_BASE_URL: /api
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    


volumes:
  postgres_data:
